# default_language_version:
#   python: python3.7
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - "--fix=lf"
      - id: trailing-whitespace
  - repo: https://github.com/jameswoolfenden/pre-commit-shell
    rev: 0.0.2
    hooks:
      - id: shell-lint
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.52.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
# terraform_tflint - Validates all Terraform configuration files with TFLint.
# tflint - TFLint is a Terraform linter focused on possible errors, best practices, and so on.
